name: vignan_chatbot
description: Vignan University AI Chatbot - Your academic assistant for personalized learning support.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.2
  flutter_tts: ^4.0.2
  flutter_markdown: ^0.7.4+9
  intl: ^0.19.0
  file_picker: ^8.0.0+1
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  mime: ^1.0.4

flutter:
  uses-material-design: true

# Optionally, define a build-time API base URL via --dart-define API_BASE_URL
# flutter run --dart-define=API_BASE_URL=http://192.168.1.100:5000/api

